// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comparisons.sql

package db

import (
	"context"
	"time"
)

const deleteComparison = `-- name: DeleteComparison :exec
DELETE FROM comparisons
WHERE id = $1
`

func (q *Queries) DeleteComparison(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComparison, id)
	return err
}

const insertComparison = `-- name: InsertComparison :exec
INSERT INTO comparisons (id, created_at, project_path, prompt, profile, series_id, attempt, series_size, criteria)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertComparisonParams struct {
	ID          string
	CreatedAt   time.Time
	ProjectPath string
	Prompt      string
	Profile     []byte
	SeriesID    string
	Attempt     int32
	SeriesSize  int32
	Criteria    []byte
}

func (q *Queries) InsertComparison(ctx context.Context, arg InsertComparisonParams) error {
	_, err := q.db.Exec(ctx, insertComparison,
		arg.ID,
		arg.CreatedAt,
		arg.ProjectPath,
		arg.Prompt,
		arg.Profile,
		arg.SeriesID,
		arg.Attempt,
		arg.SeriesSize,
		arg.Criteria,
	)
	return err
}

const insertSide = `-- name: InsertSide :exec
INSERT INTO comparison_sides (comparison_id, side, config, cli_version, status, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSideParams struct {
	ComparisonID string
	Side         string
	Config       []byte
	CliVersion   string
	Status       string
	UpdatedAt    time.Time
}

func (q *Queries) InsertSide(ctx context.Context, arg InsertSideParams) error {
	_, err := q.db.Exec(ctx, insertSide,
		arg.ComparisonID,
		arg.Side,
		arg.Config,
		arg.CliVersion,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const listComparisons = `-- name: ListComparisons :many
SELECT id, created_at, project_path, prompt, profile, report_status, report, cleaned_at, series_id, attempt, series_size, series_stopped, criteria, user_verdict
FROM comparisons
ORDER BY created_at DESC
`

func (q *Queries) ListComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comparison
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ProjectPath,
			&i.Prompt,
			&i.Profile,
			&i.ReportStatus,
			&i.Report,
			&i.CleanedAt,
			&i.SeriesID,
			&i.Attempt,
			&i.SeriesSize,
			&i.SeriesStopped,
			&i.Criteria,
			&i.UserVerdict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSides = `-- name: ListSides :many
SELECT comparison_id, side, config, cli_version, status, end_reason, run_started_at, ended_at, updated_at, phases, price_snapshot, container_id, proxy, logs, terminal, token, failure, result, inputs
FROM comparison_sides
`

func (q *Queries) ListSides(ctx context.Context) ([]ComparisonSide, error) {
	rows, err := q.db.Query(ctx, listSides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparisonSide
	for rows.Next() {
		var i ComparisonSide
		if err := rows.Scan(
			&i.ComparisonID,
			&i.Side,
			&i.Config,
			&i.CliVersion,
			&i.Status,
			&i.EndReason,
			&i.RunStartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
			&i.Phases,
			&i.PriceSnapshot,
			&i.ContainerID,
			&i.Proxy,
			&i.Logs,
			&i.Terminal,
			&i.Token,
			&i.Failure,
			&i.Result,
			&i.Inputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleaned = `-- name: MarkCleaned :exec
UPDATE comparisons
SET cleaned_at = $2
WHERE id = $1
`

type MarkCleanedParams struct {
	ID        string
	CleanedAt *time.Time
}

func (q *Queries) MarkCleaned(ctx context.Context, arg MarkCleanedParams) error {
	_, err := q.db.Exec(ctx, markCleaned, arg.ID, arg.CleanedAt)
	return err
}

const saveReport = `-- name: SaveReport :exec
UPDATE comparisons
SET report_status = $2,
    report        = $3
WHERE id = $1
`

type SaveReportParams struct {
	ID           string
	ReportStatus string
	Report       []byte
}

func (q *Queries) SaveReport(ctx context.Context, arg SaveReportParams) error {
	_, err := q.db.Exec(ctx, saveReport, arg.ID, arg.ReportStatus, arg.Report)
	return err
}

const saveSide = `-- name: SaveSide :exec
UPDATE comparison_sides
SET status         = $3,
    end_reason     = $4,
    run_started_at = $5,
    ended_at       = $6,
    updated_at     = $7,
    phases         = $8,
    price_snapshot = $9,
    container_id   = $10,
    proxy          = $11,
    logs           = $12,
    token          = $13,
    failure        = $14,
    result         = $15,
    inputs         = $16,
    terminal       = coalesce($17, terminal)
WHERE comparison_id = $1
  AND side = $2
`

type SaveSideParams struct {
	ComparisonID  string
	Side          string
	Status        string
	EndReason     string
	RunStartedAt  *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	Phases        []byte
	PriceSnapshot []byte
	ContainerID   string
	Proxy         []byte
	Logs          []byte
	Token         string
	Failure       string
	Result        []byte
	Inputs        []byte
	Terminal      []byte
}

func (q *Queries) SaveSide(ctx context.Context, arg SaveSideParams) error {
	_, err := q.db.Exec(ctx, saveSide,
		arg.ComparisonID,
		arg.Side,
		arg.Status,
		arg.EndReason,
		arg.RunStartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.Phases,
		arg.PriceSnapshot,
		arg.ContainerID,
		arg.Proxy,
		arg.Logs,
		arg.Token,
		arg.Failure,
		arg.Result,
		arg.Inputs,
		arg.Terminal,
	)
	return err
}

const saveUserVerdict = `-- name: SaveUserVerdict :exec
UPDATE comparisons
SET user_verdict = $2
WHERE id = $1
`

type SaveUserVerdictParams struct {
	ID          string
	UserVerdict []byte
}

func (q *Queries) SaveUserVerdict(ctx context.Context, arg SaveUserVerdictParams) error {
	_, err := q.db.Exec(ctx, saveUserVerdict, arg.ID, arg.UserVerdict)
	return err
}

const stopSeries = `-- name: StopSeries :exec
UPDATE comparisons
SET series_stopped = true
WHERE series_id = $1
`

func (q *Queries) StopSeries(ctx context.Context, seriesID string) error {
	_, err := q.db.Exec(ctx, stopSeries, seriesID)
	return err
}
