// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comparisons.sql

package db

import (
	"context"
	"time"
)

const insertComparison = `-- name: InsertComparison :exec
INSERT INTO comparisons (id, created_at, project_path, prompt, profile)
VALUES ($1, $2, $3, $4, $5)
`

type InsertComparisonParams struct {
	ID          string
	CreatedAt   time.Time
	ProjectPath string
	Prompt      string
	Profile     []byte
}

func (q *Queries) InsertComparison(ctx context.Context, arg InsertComparisonParams) error {
	_, err := q.db.Exec(ctx, insertComparison,
		arg.ID,
		arg.CreatedAt,
		arg.ProjectPath,
		arg.Prompt,
		arg.Profile,
	)
	return err
}

const insertSide = `-- name: InsertSide :exec
INSERT INTO comparison_sides (comparison_id, side, config, cli_version, status, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSideParams struct {
	ComparisonID string
	Side         string
	Config       []byte
	CliVersion   string
	Status       string
	UpdatedAt    time.Time
}

func (q *Queries) InsertSide(ctx context.Context, arg InsertSideParams) error {
	_, err := q.db.Exec(ctx, insertSide,
		arg.ComparisonID,
		arg.Side,
		arg.Config,
		arg.CliVersion,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const listComparisons = `-- name: ListComparisons :many
SELECT id, created_at, project_path, prompt, profile
FROM comparisons
ORDER BY created_at DESC
`

func (q *Queries) ListComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comparison
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ProjectPath,
			&i.Prompt,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSides = `-- name: ListSides :many
SELECT comparison_id, side, config, cli_version, status, end_reason, run_started_at, ended_at, updated_at, phases, price_snapshot, container_id, proxy, logs, terminal
FROM comparison_sides
`

func (q *Queries) ListSides(ctx context.Context) ([]ComparisonSide, error) {
	rows, err := q.db.Query(ctx, listSides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparisonSide
	for rows.Next() {
		var i ComparisonSide
		if err := rows.Scan(
			&i.ComparisonID,
			&i.Side,
			&i.Config,
			&i.CliVersion,
			&i.Status,
			&i.EndReason,
			&i.RunStartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
			&i.Phases,
			&i.PriceSnapshot,
			&i.ContainerID,
			&i.Proxy,
			&i.Logs,
			&i.Terminal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSide = `-- name: SaveSide :exec
UPDATE comparison_sides
SET status         = $3,
    end_reason     = $4,
    run_started_at = $5,
    ended_at       = $6,
    updated_at     = $7,
    phases         = $8,
    price_snapshot = $9,
    container_id   = $10,
    proxy          = $11,
    logs           = $12,
    terminal       = coalesce($13, terminal)
WHERE comparison_id = $1
  AND side = $2
`

type SaveSideParams struct {
	ComparisonID  string
	Side          string
	Status        string
	EndReason     string
	RunStartedAt  *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	Phases        []byte
	PriceSnapshot []byte
	ContainerID   string
	Proxy         []byte
	Logs          []byte
	Terminal      []byte
}

func (q *Queries) SaveSide(ctx context.Context, arg SaveSideParams) error {
	_, err := q.db.Exec(ctx, saveSide,
		arg.ComparisonID,
		arg.Side,
		arg.Status,
		arg.EndReason,
		arg.RunStartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.Phases,
		arg.PriceSnapshot,
		arg.ContainerID,
		arg.Proxy,
		arg.Logs,
		arg.Terminal,
	)
	return err
}
