// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Comparison struct {
	ID          string
	CreatedAt   time.Time
	ProjectPath string
	Prompt      string
	Profile     []byte
}

type ComparisonSide struct {
	ComparisonID  string
	Side          string
	Config        []byte
	CliVersion    string
	Status        string
	EndReason     string
	RunStartedAt  *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	Phases        []byte
	PriceSnapshot []byte
	ContainerID   string
	Proxy         []byte
	Logs          []byte
	Terminal      []byte
}
